### PR TITLE
Bug fix for indices.py function pe

### PR DESCRIPTION
**Pull request by tbongiov**

### CODE REVIEW

**Comment by timcera** [comment]
Hi Tara!
Was this a problem in tsutils._normalize_units?  Can you post the error?

**Comment by tbongiov** [comment]
> Hi Tara! Was this a problem in tsutils._normalize_units? Can you post the error?

Yes, the error was in tsutils._normalize_units
error_message

**Comment by timcera** [comment]
I don't have an easy test for this, but could you try:

    pe_data = tsd["rainfall:mm"] - tsd["pet:mm"]
    pe_data = tsutils.common_kwds(input_tsd=pe_data, source_units=["mm"], target_units=target_units)

The tsutils._normalize_units shouldn't be used by anything other the tsutils.common_kwds.  Obviously I broke that rule.

**Comment by tbongiov** [comment]
The tsutils.common_kwds fix does work. 
Thanks.

**Comment by timcera** [comment]
Excellent!   Thank you for testing!  I am going to change the _normalize_units function call to the common_kwds call.  Throughout all of the toolboxes the _normalize_units function is only used twice - both in mettoolbox.

**Comment by timcera** [comment]
This fix was made some time ago and just getting to closing this PR.

**Pull request closed without merging**
